name: Build and Upload iOS App

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app

      - name: Build the app
        run: make build

      - name: Archive the app
        run: make archive

      - name: Export the .ipa file
        run: make ipa

      - name: Upload the .ipa file
        uses: actions/upload-artifact@v3
        with:
          name: iOS App
          path: ./build/YourApp.ipa
